### ISSUE TITLE
Intel AMT web server does not listen on port 16994 and 16995

### ISSUE THREAD

**Issue by yanaimoyal** [travisbgreen/intel_amt_honeypot#1]
the Intel AMT web server listen only on following ports: 16992, 16993, 623 and 664

More info at https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/WordDocuments/manageabilityports.htm

Also note 16993 and 664 are HTTPS, so either drop listening on these ports or add support for SSL/TLS on these ports. I would suggest to drop these 2 ports since Intel AMT won't list on 16993 and 664 if not configured with TLS.

**Comment by travisbgreen** [comment]
Thank you, I will update asap. You are also welcome to submit PR.

**Comment by travisbgreen** [comment]
Updated, thanks!
